[package]
name = "kzg-commitments"
version = "0.1.0"
edition = "2024"

[dependencies]
ark-bls12-377 = "0.5.0"
ark-bls12-381 = "0.5.0"
ark-bn254 = "0.5.0"
ark-ec = "0.5.0"
ark-ff = "0.5.0"
ark-poly = "0.5.0"
ark-std = "0.5.0"
criterion = "0.7.0"

[[bench]]
name = "djba21_benchmarks"
harness = false
